sudo: required

language: bash

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - ES_VERSION=7.6.2
  - ES_VERSION=6.8.8
  - ES_VERSION=5.6.16

install:
  # Build the Docker image that we're going to use for testing
  - docker build --build-arg ES_VERSION=${ES_VERSION} -t ${TRAVIS_REPO_SLUG} .

before_script: >
  docker run \
    -d \
    -p 127.0.0.1:9200:9200 \
    -e "discovery.type=single-node" \
    -e "xpack.security.enabled=false" \
    ${TRAVIS_REPO_SLUG}

script:
  # Wait for Elasticsearch to start accepting incoming connections
  - wget --retry-connrefused --tries=30 --wait=1 --spider --quiet http://127.0.0.1:9200/

  # Start testing!
  - script/test.sh
